### ISSUE TITLE
Shellmet instrument

### ISSUE THREAD

**Issue by WedgeTalon** [h267/Super-Mario-Maestro#10]
The shellmet/buzzy beetle is definitely not a "reverb cowbell". [This wiki source](https://supermariomaker2.fandom.com/wiki/Note_Block) lists it as a "Detuned bell", but that is not an instrument present in the MIDI standard. The closest I can find is a lower octave Glockenspiel. (The above source lists the icicle as a "synth glockenspiel", but to my ear the icicle is a steel drum.)

**Comment by h267** [comment]
Changed to "Detuned Bell", at least the name is a little more accurate.
