### ISSUE TITLE
Drum sounds

### ISSUE THREAD

**Issue by WedgeTalon** [h267/Super-Mario-Maestro#9]
All unpitched drum kit sounds are interpreted as Goomba (piano), probably because in a MIDI file unpitched percussion uses the default (Piano) instrument on Channel 10, and the drum sound used is determined by which note is played. Effected instrument sounds include: kick drum, crash cymbal, hi-hat, snare drum, cowbell (yoshi egg, not present currently).

https://en.wikipedia.org/wiki/General_MIDI#Percussion

[UnpitchedDrums.zip](https://github.com/h267/Super-Mario-Maestro/files/4112356/UnpitchedDrums.zip)

**Comment by h267** [comment]
This issue is fixed in recent commits. Support for MIDI Channel 10 and the various types of percussion have been implemented, and the attached MIDI translates into different percussion instruments.
